CREATE TABLE DEPARTMENT ( 
DepartmentID INT PRIMARY KEY, 
DepartmentName VARCHAR(100) NOT NULL UNIQUE 
);
SELECT* FROM DEPARTMENT;


CREATE TABLE DESIGNATION ( 
DesignationID INT PRIMARY KEY, 
DesignationName VARCHAR(100) NOT NULL UNIQUE 
);
SELECT* FROM DESIGNATION;

CREATE TABLE PERSON ( 
PersonID INT PRIMARY KEY IDENTITY(101,1), 
FirstName VARCHAR(100) NOT NULL, 
LastName VARCHAR(100) NOT NULL, 
Salary DECIMAL(8, 2) NOT NULL, 
JoiningDate DATETIME NOT NULL, 
DepartmentID INT NULL, 
DesignationID INT NULL, 
FOREIGN KEY (DepartmentID) REFERENCES Department(DepartmentID), 
FOREIGN KEY (DesignationID) REFERENCES Designation(DesignationID) 
);

SELECT* FROM PERSON;

DROP TABLE DEPARTMENT
DROP TABLE PERSON
DROP TABLE DESIGNATION
