CREATE TABLE PERSON(
	PERSON_ID INT,
	PERSON_NAME VARCHAR(100),
	DEPARTMENT_ID INT,
	SALARY DECIMAL(8,2),
	JOINING_DATE DATETIME,
	CITY VARCHAR(100)
);
CREATE TABLE DEPT(
	DEPARTMENT_ID INT,
	DEPARTMENT_NAME VARCHAR(100),
	DEPARTMENT_CODE VARCHAR(50),
	LOCATION VARCHAR(50)

);
SELECT * FROM DEPT;
